### ISSUE TITLE
Blank page on Google Chrome

### ISSUE THREAD

**Issue by rdymac** [greenaddress/gentle#2]
If you open the downloaded index.html in the package from GitHub in Chrome it shows a green background and nothing else.

It works correctly on Safari 7.0.3

**Comment by gurnec** [comment]
Chrome believes that any uri accessed via the file: scheme violates the same-origin policy.

The workaround is to close Chrome, and then run it with the `--disable-web-security` option (just don't forget to close and re-open Chrome before browsing the web).

 It looks like gentle uses `XMLHttpRequest` fairly often (the partial1 template, the english.txt file, the mnemonic_seed Worker(), probably others too), so it seems difficult and not very productive to rewrite it all. Perhaps a better approach would be to detect Chrome in index.html and display some instructions on how to work around this?

**Comment by greenaddress** [comment]
It actually works on Chrome now but it has to be either served from a web server (python comes handy) or you need to start chrome/chromium with a flag: `--allow-file-access-from-files`.

The README is now updated to note this. Closing.
